### ISSUE TITLE
Can't Pass the Spec: describe 'POST /' do     it "displays string results" do

### ISSUE THREAD

**Issue by ShiLi007** [learn-co-curriculum/sinatra-integrating-models-walkthrough#11]
describe 'POST /' do
    it "displays string results" do 
      visit '/'

      fill_in(:user_text, :with => "Green Eggs and Ham")
      click_button "submit"
      expect(page).to have_text("Number of Words:4")
      expect(page).to have_text("Vowels:5")
      expect(page).to have_text("Consonants:10")
      expect(page).to have_text("Most Common Letter: G, used 3 times")
    end
  end

for the phrase "Green Eggs and Ham", there are 4 Vowels and 8 Consonants.

**Comment by mendelB** [comment]
Hi @ShiLi007 Thanks for this submission!!
We're counting the upper case letters as well which makes it 10 and 5 ;)
I'm going to go ahead and close this issue. Thanks again!
