### ISSUE TITLE
rspec does not run because spec/spec_helper.rb is missing a line of code

### ISSUE THREAD

**Issue by jin501** [learn-co-curriculum/sinatra-integrating-models-walkthrough#15]
spec/spec_helper.rb needs to require 'capybara/rspec'
in order for rspec to run

**Comment by gj** [comment]
Hi there,

The test suite seems to work fine. I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
