### ISSUE TITLE
Testing issue

### ISSUE THREAD

**Issue by jminterwebs** [learn-co-curriculum/sinatra-integrating-models-walkthrough#16]
The rspec tests are using "Green Eggs and Ham" while the model is only counting lower case letters.

    ` def count_of_vowels
    @text.scan(/[aeoui]/).count
  end

  def count_of_consonants
    @text.scan(/[bcdfghjklmnpqrstvwxyz]/).count
  end
`

`describe 'POST /' do
    it "displays string results" do 
      visit '/'

      fill_in(:user_text, :with => "Green Eggs and Ham")
      click_button "submit"
      expect(page).to have_text("Number of Words:4")
      expect(page).to have_text("Vowels:5")
      expect(page).to have_text("Consonants:10")
      expect(page).to have_text("Most Common Letter: G, used 3 times")
    end
`

**Comment by gj** [comment]
Fixed; thanks @jminterwebs !
