### ISSUE TITLE
rspec error

### ISSUE THREAD

**Issue by 1m53ri0us** [learn-co-curriculum/sinatra-integrating-models-walkthrough#18]
the test is trying to pull data from a hash
but the method stores the outcome as an array

**Comment by gj** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
