### ISSUE TITLE
description of post route in the lab's instructions differs from cloned lab content 

### ISSUE THREAD

**Issue by ode-to-the-code** [learn-co-curriculum/sinatra-integrating-models-walkthrough#19]
When I cloned down the lab, the controller's post route had no 'results'  after the slash. It just looked like this:

post '/' do
  text_from_user = params[:user_text]
  erb :results
end

But in the original description from the lab it says to expect a '/results' route:

"The controller has two routes:

get '/' do, which renders the index.erb page.
**post '/results'** do, which receives the form data through params and renders the results page."

**Comment by gj** [comment]
Fixed in #14. Thanks @ode-to-the-code !
