### ISSUE TITLE
Tests not passing 

### ISSUE THREAD

**Issue by SaraMSchwarz** [learn-co-curriculum/sinatra-integrating-models-walkthrough#22]
My tests were not passing after completing the walkthrough and during AAQ it was noticed that I needed to require 'capybara/dsl' \on line 4 of spec_helper.rb.

**Comment by ThePeej** [comment]
Just ran into this same issue, and the missing require issue remains. The above suggestion fixes the issue, and is a good temp fix until that line gets added to the master to be included from the start

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. We updated spec_helper.rb.

As always thank you for contributing!
