### ISSUE TITLE
spec issue with Integrating Models for a Full MVC

### ISSUE THREAD

**Issue by Burrick2003** [learn-co-curriculum/sinatra-integrating-models-walkthrough#25]
This was just an example cut-n-paste lab, running learn gave this:
bundler: failed to load command: rspec (/usr/local/rvm/gems/ruby-2.3.1/bin/rspec)
NameError: uninitialized constant Capybara::DSL

So I compared to previous and added to spec_helper.rb:
require 'capybara/rspec'
require 'capybara/dsl'

...and learn ran fine, I was able to submit.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. We updated spec_helper.rb.

As always thank you for contributing!
