### ISSUE TITLE
require 'capybara/dsl' not included in controller app.rb - must include this for program to work

### ISSUE THREAD

**Issue by alexcrisan** [learn-co-curriculum/sinatra-integrating-models-walkthrough#26]
Also, there already exists a model file called text_analyzer.rb, which is also required in the controller file. This file does not need to exist, since we are told to create the file textanalyzer.rb. This should be deleted as it confuses the students.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. We updated spec_helper.rb.

As always thank you for contributing!
