### ISSUE TITLE
missing line from spec_helper.rb

### ISSUE THREAD

**Issue by jokerdelta** [learn-co-curriculum/sinatra-integrating-models-walkthrough#27]
The following line is missing from the spec_helper file, which causes an rspec error when you try and run the tests.  

require 'capybara/dsl'

Once I added it, everything seamed to work fine.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. We updated spec_helper.rb.

As always thank you for contributing!
