### ISSUE TITLE
Cleaner implementation of most_used_letter

### ISSUE THREAD

**Issue by safuya** [learn-co-curriculum/sinatra-integrating-models-walkthrough#28]
This is a refactored version of the most used letter method.
```
def most_used_letter
  no_spaces = text.gsub(" ", "")
  letters = no_spaces.split("")
  histogram = Hash[*letters.group_by{ |v| v }.flat_map{ |k, v| [k, v.size] }]
  histogram.max_by{ |k, v| v }
end
```

**Comment by maxwellbenton** [comment]
Thank you for spotting this and providing feedback.  We have tested this method updated our solution branch to reflect this.  Thank you for contributing a great solution! 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
