### ISSUE TITLE
Fix Errors in README

### ISSUE THREAD

**Issue by unenlightened** [learn-co-curriculum/sinatra-integrating-models-walkthrough#29]
Line 86 -- At the top of app.rb, add require_relative "models/textanalyzer.rb".  
  - change filename to match -> At the top of app.rb, add require_relative "models/text_analyzer.rb".  

Line 80 -- my_text.most_used_letter #=> ["n", 6]
 - output from the method is actually a hash not an array -> my_text.most_used_letter #=> {"n"=>6}

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
