### ISSUE TITLE
Duplicate models files

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/sinatra-integrating-models-walkthrough#31]
The ReadMe for this lab says: "In your models directory, create a new file called textanalyzer.rb." However, there is already a file in that directory called text_analyzer.rb (with underscore). That file has a comment at the top that says # Your TextAnalyzer model code will go here. The ReadMe goes on to say "Instead, paste the following code in to your textanalyzer.rb file," but then conflicts itself by instructing "At the top of app.rb, add require_relative "models/text_analyzer.rb" [with underscore]

Seems like the ReadMe should be updated to reflect using the existing file (with underscore) and not creating a new one or pasting anything into it.

Thank you.

**Comment by cjbrock** [comment]
Hi @ValerieHMoore! You're absolutely right - that's a silly thing to do. I've updated the README so we're directing the students to use the file we're already providing. Thanks for pointing this out for us. I've noticed you're taking a lot of your time helping make our curriculum a better place for students to learn, and I really appreciate it! You're doing a really great job. Not a lot of our students take their time to do that. 
// <3 Corinna
