### ISSUE TITLE
Tiny wording change

### ISSUE THREAD

**Issue by bubbaspaarx** [learn-co-curriculum/sinatra-integrating-models-walkthrough#32]
in the paragraph it asks to create a new file called textanalyzer.rb but there is already a file in the models folder and it is formatted as text_analyzer.rb

**Comment by cjbrock** [comment]
Hey @bubbaspaarx! Thanks for pointing that out - I've changed the wording in the README to point the students to use the file that we've already provided for them. Thanks for helping make Learn a better place. 
// Corinna
