### ISSUE TITLE
README example class needs instance variables in TextAnalyzer

### ISSUE THREAD

**Issue by big32mike** [learn-co-curriculum/sinatra-integrating-models-walkthrough#34]
The :text attr_reader gets set in the initialize method, but isn't referred to as an instance variable in the instance methods of the TextAnalyzer class.

**Comment by Sdcrouse** [comment]
I believe that's because when the instance methods are using `text` instead of `@text`, they're REALLY calling the `#text` reader method, which returns the `@text` instance variable.

Remember that `attr_reader :text` is equivalent to this:
```
def text
  @text
end
```

I hope that helps!

---Sdcrouse

**Comment by drakeltheryuujin** [comment]
Thanks for your contribution! It seems that this question may have been resolved?
If you do not believe that this issue has been addressed, please re-open this issue. 💙
